name: CI Test Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_MOCK_GEMINI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov playwright
          playwright install

      - name: Install frontend dependencies
        working-directory: ./fitcheck
        run: npm install

      - name: Build Next.js app
        working-directory: ./fitcheck
        run: npm run build

      - name: Start Next.js server in background
        run: |
          cd fitcheck
          NEXT_PUBLIC_MOCK_GEMINI=true nohup npm run start &

      - name: Wait for server to be ready
        run: |
          sleep 10
          curl --retry 5 --retry-delay 5 --fail http://localhost:3000 || exit 1

      - name: Run Python tests with coverage
        run: pytest --cov=./ --cov-report=html

      - name: Run Playwright E2E test
        run: python tests/test_login_e2e.py

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov
